Repository eclipse-ankaios/ankaios, pull requests merged in 2023-09, with the labels that each got.

#37 Add final result to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: ignore-for-release, ready for review

#40 Allow command entry in Podman RuntimeConfig to overrides image's entrypoint - preparations
  agent/src/podman/mod.rs
  agent/src/podman/podman_adapter.rs
  agent/src/podman/podman_runtime_config.rs
  agent/src/podman/podman_utils.rs
  agent/src/podman/workload.rs
Labels: ready for review

#43 Add task list check Github Action workflow
  .github/workflows/task-list-check.yml
Labels: enhancement

#45 Override image's entrypoint
  agent/src/podman/podman_runtime_config.rs
  agent/src/podman/podman_utils.rs
  doc/docs/reference/startup-configuration.md
Labels: ready for review

#47 Provide releases for documentation
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.base
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  .github/workflows/documentation.yml
  .github/workflows/release.yml
  doc/mkdocs.yml
  doc/overrides/main.html
  examples/workload_api_example/Dockerfile
  tools/generate_docs.sh
Labels: ignore-for-release, ready for review

#51 Support Podman network mode
  agent/src/podman/podman_runtime_config.rs
  agent/src/podman/podman_utils.rs
  doc/docs/reference/startup-configuration.md
Labels: ready for review
