Repository eclipse-ankaios/ankaios, pull requests merged in 2023-11, with the labels that each got.

#76 Fix field masks in Ankaios CLI help messages
  ank/src/cli.rs
  api/proto/ankaios.proto
Labels: ready for review

#66 Update contribution guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  doc/docs/development/requirement-tracing.md
  doc/docs/support.md
  doc/mkdocs.yml
Labels: documentation, ready for review

#61 Add startup automation to installation
  doc/docs/usage/installation.md
  doc/docs/usage/quickstart.md
  tools/install.sh
Labels: enhancement

#81 Add environment variable support for server url in Ankaios CLI
  ank/Cargo.toml
  ank/doc/swdesign/README.md
  ank/src/cli.rs
  ank/src/main.rs
Labels: ready for review

#88 Remove task list check GH action
  .github/workflows/task-list-check.yml
Labels: ready for review

#98 Update dependencies
  Cargo.lock
  deny.toml
Labels: ready for review

#97 Update documentation on Podman version and quickstart
  doc/docs/reference/control-interface.md
  doc/docs/usage/installation.md
  doc/docs/usage/quickstart.md
  tools/generate_docs.sh
Labels: documentation, ready for review

#87 Add cache for podman ps
  agent/doc/swdesign/README.md
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman_cli.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
  common/src/objects/workload_spec.rs
  common/src/test_utils.rs
  tests/stests/workloads/update_workload.robot
Labels: ready for review

#101 Compile the production code by the rust_analyzer
  .vscode/settings.json
Labels: ready for review

#102 Fix new workload always having the state "removed"
  agent/doc/swdesign/README.md
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman_cli.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
Labels: bug

#96 Improve and stabilize system tests
  .github/workflows/build.yml
  agent/doc/swdesign/README.md
  tests/resources/ankaios.resource
  tests/resources/ankaios_library.py
  tests/stests/workloads/create_workload_podman.robot
  tests/stests/workloads/create_workload_podman_kube.robot
  tests/stests/workloads/create_workloads.robot
  tests/stests/workloads/delete_workload_podman.robot
  tests/stests/workloads/delete_workload_podman_kube.robot
  tests/stests/workloads/list_workloads.robot
  tests/stests/workloads/update_workload.robot
  tests/stests/workloads/update_workload_podman.robot
  tools/run_robot_tests.sh
Labels: ready for review

#103 Use Vagrant for provisioning test VMs
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  tools/vagrant/README.md
  tools/vagrant/ubuntu20.04/Vagrantfile
  tools/vagrant/ubuntu20.04/init.sh
  tools/vagrant/ubuntu22.04/Vagrantfile
  tools/vagrant/ubuntu22.04/init.sh
  tools/vagrant/ubuntu23.04/Vagrantfile
  tools/vagrant/ubuntu23.04/init.sh
Labels: enhancement, ready for review

#108 Pinpoint ignored coverage files
  agent/src/runtime_connectors/podman/podman_runtime.rs
  grpc/src/state_change_proxy.rs
  tools/generate_test_coverage_report.sh
Labels: ready for review
