Repository eclipse-ankaios/ankaios, pull requests merged in 2023-12, with the labels that each got.

#120 Workaround for Podman problems with inconsistent Podman DB
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman_cli.rs
  tools/stability_manual_test.sh
Labels: ready for review

#111 Ankaios server shall exits if the configured gRPC port is already in use
  agent/src/control_interface/directory.rs
  agent/src/control_interface/fifo.rs
  agent/src/control_interface/filesystem.rs
  agent/src/control_interface/input_output.rs
  ank/src/cli_commands.rs
  common/src/communications_server.rs
  common/src/objects/access_rights.rs
  common/src/objects/workload_spec.rs
  grpc/src/client.rs
  grpc/src/execution_command_proxy.rs
  grpc/src/grpc_middleware_error.rs
  grpc/src/lib.rs
  grpc/src/proxy_error.rs
  grpc/src/server.rs
  grpc/src/state_change_proxy.rs
  grpc/tests/grpc_test.rs
  server/src/main.rs
Labels: enhancement

#125 Improve execution states
  agent/doc/swdesign/README.md
  agent/src/parameter_storage.rs
  agent/src/runtime_connectors/podman_cli.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
  agent/src/runtime_connectors/state_checker.rs
  api/proto/ankaios.proto
  common/src/objects/workload_state.rs
  server/src/workload_state_db.rs
Labels: ready for review

#124 Added wait for complete state in cli
  ank/src/cli_commands.rs
  ank/src/main.rs
Labels: ready for review

#129 Add release preparation steps for releases
  doc/docs/development/ci-cd-release.md
Labels: ready for review

#127 Handle all Podman states
  agent/doc/swdesign/README.md
  agent/src/runtime_connectors/podman_cli.rs
Labels: ready for review

#133 Update version to 0.3.0-pre
  Cargo.lock
  Cargo.toml
  agent/Cargo.toml
  ank/Cargo.toml
  api/Cargo.toml
  common/Cargo.toml
  examples/README.md
  examples/run_example.sh
  examples/rust_control_interface/Cargo.lock
  examples/rust_control_interface/Cargo.toml
  grpc/Cargo.toml
  server/Cargo.toml
Labels: ready for review

#140 Fix markdown lint in CI builds
  .github/workflows/documentation.yml
Labels: bug, ignore-for-release, ready for review

#141 Use cargo-deny for license checks
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.base
  .github/workflows/build.yml
  .github/workflows/documentation.yml
  Cargo.lock
Labels: enhancement, ready for review

#143 Fix sequence diagram of update workload
  agent/doc/swdesign/README.md
  agent/doc/swdesign/plantuml/seq_update_workload.plantuml
  agent/doc/swdesign/plantuml/seq_update_workload.svg
Labels: documentation, ready for review

#144 Adding required execution states and conditions for the inter-workload dependencies
  agent/src/runtime_connectors/podman_cli.rs
  ank/src/cli_commands.rs
  api/proto/ankaios.proto
  common/doc/swdesign/README.md
  common/doc/swdesign/plantuml/seq_example.plantuml
  common/doc/swdesign/plantuml/state_workload_execution_states.plantuml
  common/doc/swdesign/plantuml/state_workload_execution_states.svg
  common/src/objects/mod.rs
  common/src/objects/workload_spec.rs
  common/src/objects/workload_state.rs
  common/src/test_utils.rs
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
  server/src/ankaios_server/update_state.rs
  server/src/state_manipulation/object.rs
  server/src/state_parser.rs
Labels: enhancement, ready for review
