Repository eclipse-ankaios/ankaios, pull requests merged in 2024-09, with the labels that each got.

#348 Add shell completion
  .devcontainer/Dockerfile
  Cargo.lock
  ank/Cargo.toml
  ank/doc/swdesign/README.md
  ank/src/cli.rs
  ank/src/main.rs
  doc/docs/usage/shell-completion.md
  doc/mkdocs.yml
Labels: ready for review

#368 Fix rootless ports not being freed
  tests/stests/mtls/mtls_communication.robot
Labels: ignore-for-release, ready for review

#373 Improve mTLS error messages for Ank CLI due to certificate errors
  grpc/src/client.rs
Labels: enhancement, ready for review

#369 Add fix for system tests to dev container
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.base
  .github/workflows/build.yml
  .github/workflows/documentation.yml
Labels: ignore-for-release, ready for review

#366 Requirements linkage fixes for list agents
  ank/src/cli_commands/get_agents.rs
  server/src/ankaios_server.rs
  server/src/ankaios_server/server_state.rs
Labels: ignore-for-release, ready for review

#367 Fix reconnected agents not getting deleted workload
  agent/src/agent_manager.rs
  agent/src/runtime_manager.rs
  common/src/commands.rs
  common/src/from_server_interface.rs
  grpc/proto/grpc_api.proto
  grpc/src/from_server_proxy.rs
  grpc/src/grpc_api.rs
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
Labels: bug, ready for review

#374 Fix naming issues
  Cargo.lock
  agent/Cargo.toml
  agent/doc/swdesign/README.md
  agent/src/cli.rs
  agent/src/main.rs
  ank/src/cli_commands/apply_manifests.rs
  api/proto/ank_base.proto
  common/Cargo.toml
  common/doc/swdesign/README.md
  common/src/objects/mod.rs
  common/src/objects/state.rs
  common/src/state_manipulation/object.rs
  doc/docs/reference/complete-state.md
  doc/docs/usage/quickstart.md
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
  tests/resources/configs/update_state_invalid_names.yaml
  tests/resources/configs/update_state_long_names.yaml
  tests/stests/agents/list_agents.robot
  tests/stests/workloads/update_workload_podman.robot
Labels: ready for review

#383 Simplify ank cli set state command
  ank/src/cli_commands/set_state.rs
  tests/resources/configs/minimal_set_state.yaml
  tests/resources/configs/update_state_create_one_workload.yaml
  tests/resources/configs/update_state_pending_create.yaml
Labels: ready for review

#381 Add just file for Ankaios
  .github/workflows/build.yml
  .vscode/settings.json
  justfile
  tools/dev_scripts/ankaios-clean
Labels: ignore-for-release, ready for review

#387 Fix log message regarding ServerHello
  server/src/ankaios_server.rs
Labels: ignore-for-release, ready for review

#385 Fix naming issues
  agent/doc/swdesign/README.md
  common/doc/swdesign/README.md
Labels: ignore-for-release, ready for review
