Repository eclipse-ankaios/ankaios, pull requests merged in 2024-10, with the labels that each got.

#375 Fix copyright headers
  .github/workflows/build.yml
  agent/src/control_interface/authorizer/rule.rs
  agent/src/generic_polling_state_checker.rs
  agent/src/runtime_connectors/cli_command.rs
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman/podman_runtime_config.rs
  agent/src/runtime_connectors/podman_cli.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime_config.rs
  agent/src/runtime_connectors/runtime_connector.rs
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/runtime_connectors/state_checker.rs
  common/src/communications_error.rs
  common/src/objects/agent_name.rs
  common/src/objects/control_interface_access.rs
  common/src/objects/workload_instance_name.rs
  grpc/tests/grpc_test.rs
  justfile
  tools/check_copyright_headers.sh
Labels: ready for review

#378 Add node resource availability
  Cargo.lock
  agent/Cargo.toml
  agent/doc/swdesign/README.md
  agent/src/agent_manager.rs
  agent/src/runtime_manager.rs
  ank/doc/swdesign/README.md
  ank/src/cli_commands/agent_table_row.rs
  ank/src/cli_commands/get_agents.rs
  ank/src/filtered_complete_state.rs
  api/proto/ank_base.proto
  common/doc/swdesign/README.md
  common/src/commands.rs
  common/src/objects/agent_map.rs
  common/src/objects/mod.rs
  common/src/state_manipulation/object.rs
  common/src/to_server_interface.rs
  doc/docs/usage/tutorial-vehicle-signals.md
  grpc/proto/grpc_api.proto
  grpc/src/grpc_api.rs
  grpc/src/to_server_proxy.rs
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
  server/src/ankaios_server/server_state.rs
  tests/resources/ankaios.resource
  tests/resources/ankaios_library.py
Labels: enhancement, ready for review

#390 Add instructions for private vulnerability reports
  SECURITY.md
Labels: ready for review

#384 Fix stucking wait mode caused by unscheduled workloads and disconnected agents variations
  ank/doc/swdesign/README.md
  ank/src/cli_commands.rs
  ank/src/cli_commands/apply_manifests.rs
  ank/src/cli_commands/delete_workloads.rs
  ank/src/cli_commands/get_workloads.rs
  ank/src/cli_commands/run_workload.rs
  ank/src/cli_commands/set_state.rs
  ank/src/cli_commands/wait_list.rs
  ank/src/filtered_complete_state.rs
  common/doc/swdesign/README.md
  common/src/objects/agent_map.rs
  common/src/objects/workload_instance_name.rs
  common/src/objects/workload_state.rs
  common/src/objects/workload_states_map.rs
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
  server/src/ankaios_server/server_state.rs
Labels: bug, ready for review

#380 Add API version checks to all connections to Ankaios
  Cargo.lock
  agent/doc/swdesign/README.md
  agent/src/control_interface/control_interface_task.rs
  agent/src/control_interface/reopen_file.rs
  agent/src/control_interface/to_ankaios.rs
  agent/src/main.rs
  api/build.rs
  api/proto/control_api.proto
  common/Cargo.toml
  common/doc/swdesign/README.md
  common/src/helpers.rs
  common/src/lib.rs
  doc/docs/usage/upgrading/v0_4_to_v0_5.md
  examples/cpp_control_interface/Dockerfile
  examples/cpp_control_interface/src/main.cpp
  examples/nodejs_control_interface/Dockerfile
  examples/nodejs_control_interface/src/main.js
  examples/python_control_interface/Dockerfile
  examples/python_control_interface/src/main.py
  examples/rust_control_interface/Dockerfile
  examples/rust_control_interface/src/main.rs
  grpc/doc/swdesign/README.md
  grpc/proto/grpc_api.proto
  grpc/src/client.rs
  grpc/src/grpc_agent_connection.rs
  grpc/src/grpc_api.rs
  grpc/src/grpc_cli_connection.rs
  grpc/src/grpc_middleware_error.rs
  tests/resources/ankaios.resource
  tests/resources/ankaios_library.py
  tests/resources/configs/simple_with_control.yaml
  tests/resources/image/Cargo.toml
  tests/resources/image/README.md
  tests/resources/image/src/main.rs
  tests/stests/control_interface/control_interface.robot
  tools/update_version.sh
Labels: enhancement

#404 Fix unstable apply manifest stest
  tests/stests/manifests/apply_manifests.robot
Labels: ignore-for-release

#386 Re-use bundles at startup for podman runtime
  .github/workflows/build.yml
  .vscode/launch.json
  agent/doc/swdesign/README.md
  agent/src/generic_polling_state_checker.rs
  agent/src/runtime_connectors/mod.rs
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman_cli.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
  agent/src/runtime_connectors/runtime_connector.rs
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/runtime_connectors/state_checker.rs
  agent/src/runtime_manager.rs
  agent/src/workload/control_loop_state.rs
  agent/src/workload/workload_control_loop.rs
  agent/src/workload_operation.rs
  agent/src/workload_scheduler/scheduler.rs
  ank/doc/swdesign/README.md
  common/src/objects/workload_state.rs
  doc/docs/development/requirement-tracing.md
  justfile
  tests/resources/ankaios.resource
  tests/resources/configs/device_restart_with_dependencies_modified_web_service_init.yaml
  tests/stests/workloads/create_workload_podman.robot
  tests/stests/workloads/device_restart_with_dependencies.robot
  tools/generate_oft_html_report.sh
Labels: enhancement, ready for review

#389 Add workload config implementation
  .vscode/settings.json
  Cargo.lock
  agent/src/cli.rs
  agent/src/runtime_manager.rs
  ank/src/cli.rs
  ank/src/cli_commands.rs
  ank/src/cli_commands/apply_manifests.rs
  common/doc/swdesign/README.md
  common/src/objects/config.rs
  common/src/objects/mod.rs
  common/src/objects/state.rs
  common/src/objects/stored_workload_spec.rs
  common/src/objects/workload_spec.rs
  common/src/state_manipulation/object.rs
  common/src/test_utils.rs
  doc/docs/reference/complete-state.md
  doc/docs/reference/startup-configuration.md
  doc/docs/usage/quickstart.md
  doc/docs/usage/tutorial-vehicle-signals.md
  examples/rust_control_interface/src/main.rs
  grpc/src/from_server_proxy.rs
  grpc/src/grpc_api.rs
  grpc/src/to_server_proxy.rs
  server/Cargo.toml
  server/doc/swdesign/README.md
  server/doc/swdesign/plantuml/seq_update_state.plantuml
  server/doc/swdesign/plantuml/seq_update_state.svg
  server/src/ankaios_server.rs
  server/src/ankaios_server/config_renderer.rs
  server/src/ankaios_server/server_state.rs
  tests/resources/ankaios.resource
  tests/resources/configs/invalid_templated_manifest.yaml
  tests/resources/configs/manifest_with_configs.yaml
  tests/resources/configs/manifest_with_configs_updated_config_item.yaml
  tests/resources/configs/update_state_invalid_config_item_key.yaml
  tests/resources/configs/update_state_invalid_workload_config_alias.yaml
  tests/resources/configs/update_state_invalid_workload_config_reference_key.yaml
  tests/stests/manifests/apply_manifests.robot
  tests/stests/workloads/update_workload_podman.robot
  tests/stests/workloads/workload_configs_podman.robot
Labels: enhancement, ready for review

#405 Fix small issues in the documentation
  doc/docs/reference/control-interface.md
  doc/mkdocs.yml
Labels: bug, ignore-for-release, ready for review

#406 Update versions and remove unused dependencies
  Cargo.lock
  agent/Cargo.toml
  ank/Cargo.toml
  common/Cargo.toml
  grpc/Cargo.toml
  server/Cargo.toml
Labels: enhancement, ignore-for-release, ready for review
