Repository eclipse-ankaios/ankaios, pull requests merged in 2024-01, with the labels that each got.

#137 Restart workloads that are added after deletion and take too much time to delete
  agent/doc/swdesign/README.md
  agent/doc/swdesign/plantuml/seq_restart_workload_on_create_failure.plantuml
  agent/doc/swdesign/plantuml/seq_restart_workload_on_create_failure.svg
  agent/doc/swdesign/plantuml/seq_restart_workload_on_update_with_create_failure.plantuml
  agent/doc/swdesign/plantuml/seq_restart_workload_on_update_with_create_failure.svg
  agent/doc/swdesign/plantuml/seq_update_workload_subsequent_added.plantuml
  agent/doc/swdesign/plantuml/seq_update_workload_subsequent_added.svg
  agent/doc/swdesign/plantuml/seq_update_workload_subsequent_deleted.plantuml
  agent/doc/swdesign/plantuml/seq_update_workload_subsequent_deleted.svg
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/workload.rs
  agent/src/workload/workload_command_channel.rs
  agent/src/workload/workload_control_loop.rs
  ank/doc/swdesign/README.md
  tests/resources/ankaios.resource
  tests/resources/configs/podman_alpine_sleep.yaml
  tests/resources/configs/podman_wrong_image_name.yaml
  tests/stests/workloads/delete_workload_podman.robot
  tests/stests/workloads/delete_workload_podman_kube.robot
  tests/stests/workloads/restart_workload_podman.robot
Labels: enhancement

#148 Clarify building Ankaios on Mac with Apple silicon
  doc/docs/development/build.md
Labels: documentation

#132 Make startup config optional
  doc/docs/usage/quickstart.md
  server/doc/swdesign/README.md
  server/doc/swdesign/plantuml/seq_startup.plantuml
  server/doc/swdesign/plantuml/seq_startup.svg
  server/src/cli.rs
  server/src/main.rs
  tests/resources/ankaios.resource
  tests/resources/configs/update_state_create_one_workload.yaml
  tests/stests/workloads/update_workload_podman.robot
Labels: enhancement, ready for review

#160 Add URL to connection error message
  grpc/src/client.rs
Labels: enhancement, ready for review

#162 Improve ank error when server not available
  common/src/communications_error.rs
Labels: enhancement, ready for review

#156 Add cyclic detection for workload dependencies and dependency graph management to Ankaios server
  .vscode/settings.json
  Cargo.lock
  server/Cargo.toml
  server/doc/swdesign/README.md
  server/doc/swdesign/plantuml/seq_get_complete_state.plantuml
  server/doc/swdesign/plantuml/seq_get_complete_state.svg
  server/doc/swdesign/plantuml/seq_startup.plantuml
  server/doc/swdesign/plantuml/seq_startup.svg
  server/doc/swdesign/plantuml/seq_update_state.plantuml
  server/doc/swdesign/plantuml/seq_update_state.svg
  server/src/ankaios_server.rs
  server/src/ankaios_server/cycle_check.rs
  server/src/ankaios_server/server_state.rs
  server/src/ankaios_server/update_state.rs
  server/src/main.rs
  server/src/workload_state_db.rs
  tests/resources/ankaios.resource
  tests/resources/configs/default_config_with_dependencies.yaml
  tests/resources/configs/state_with_dependency_cycle.yaml
  tests/resources/configs/update_state_config_with_dependency_cycle.yaml
  tests/stests/workloads/reject_state_with_cyclic_dependencies.robot
Labels: enhancement, ready for review

#154 Ankaios CLI "ank get workloads" does not list workload state "Stopping"
  ank/doc/swdesign/README.md
  ank/src/cli_commands.rs
  server/doc/swdesign/README.md
  tests/stests/workloads/delete_workload_podman.robot
  tests/stests/workloads/delete_workload_podman_kube.robot
  tests/stests/workloads/restart_workload_podman.robot
Labels: ready for review
