Repository eclipse-ankaios/ankaios, pull requests merged in 2024-07, with the labels that each got.

#299 Refactor and improve CLI code
  ank/doc/swdesign/README.md
  ank/src/cli_commands.rs
  ank/src/cli_commands/apply_manifests.rs
  ank/src/cli_commands/delete_workloads.rs
  ank/src/cli_commands/get_state.rs
  ank/src/cli_commands/get_workloads.rs
  ank/src/cli_commands/run_workload.rs
  ank/src/cli_commands/set_state.rs
  ank/src/cli_commands/wait_list_display.rs
  ank/src/cli_commands/workload_table_row.rs
  ank/src/cli_error.rs
  ank/src/main.rs
Labels: ready for review

#303 Fix ank flickering with additional wrap and truncate
  agent/doc/swdesign/README.md
  agent/src/runtime_connectors/cli_command.rs
  agent/src/workload/workload_command_channel.rs
  agent/src/workload/workload_control_loop.rs
  ank/doc/swdesign/README.md
  ank/src/cli_commands.rs
  ank/src/cli_commands/delete_workloads.rs
  ank/src/cli_commands/get_state.rs
  ank/src/cli_commands/get_workloads.rs
  ank/src/cli_commands/run_workload.rs
  ank/src/cli_commands/set_state.rs
  ank/src/cli_commands/wait_list.rs
  ank/src/cli_commands/wait_list_display.rs
  ank/src/cli_commands/workload_table.rs
  ank/src/cli_commands/workload_table_row.rs
  ank/src/cli_error.rs
  ank/src/log.rs
  common/doc/swdesign/drawio/state_workload_execution_all_states.drawio.svg
  common/src/objects/workload_state.rs
  tests/resources/ankaios_library.py
  tests/stests/workloads/retry_creation_of_workload_podman.robot
Labels: bug

#305 Fix agent sending old workload states after workload was updated
  agent/doc/swdesign/README.md
  agent/src/workload/workload_control_loop.rs
Labels: bug

#310 Fix linkage of bug fix agent sends old workload states of updated workload
  agent/doc/swdesign/README.md
  agent/src/workload/workload_control_loop.rs
  tests/stests/workloads/restart_handling_podman.robot
  tests/stests/workloads/restart_handling_podman_kube.robot
Labels: bug, ignore-for-release

#315 Fix documentation for the dev container
  doc/docs/development/build.md
Labels: documentation, ready for review

#314 Fix uncovered swdds with missing utest and stest
  ank/doc/swdesign/README.md
  ank/src/cli_commands.rs
  ank/src/cli_commands/apply_manifests.rs
  ank/src/cli_commands/delete_workloads.rs
  ank/src/cli_commands/run_workload.rs
  ank/src/cli_commands/set_state.rs
  ank/src/cli_commands/wait_list.rs
  common/doc/swdesign/README.md
  server/doc/swdesign/README.md
  server/src/main.rs
Labels: ignore-for-release, ready for review

#319 Remove WorkloadStateDB from Software Design documentation
  server/doc/swdesign/README.md
  server/doc/swdesign/drawio/comp_overview.drawio.svg
  server/doc/swdesign/plantuml/seq_set_wl_state_on_disconnected.plantuml
  server/doc/swdesign/plantuml/seq_set_wl_state_on_disconnected.svg
  server/doc/swdesign/plantuml/seq_wl_state_update.plantuml
  server/doc/swdesign/plantuml/seq_wl_state_update.svg
Labels: ready for review

#327 Remove not needed podman kube runtime types
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
Labels: ignore-for-release, ready for review

#328 Small improvements of the dev environment
  .devcontainer/devcontainer.json
  Cargo.lock
  common/Cargo.toml
  common/src/state_manipulation/object.rs
Labels: ignore-for-release, ready for review

#318 Fix the filtering of the complete state
  Cargo.lock
  agent/doc/swdesign/README.md
  agent/src/agent_manager.rs
  agent/src/control_interface/pipes_channel_task.rs
  agent/src/control_interface/to_ankaios.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
  agent/src/runtime_manager.rs
  agent/src/workload.rs
  ank/Cargo.toml
  ank/src/cli_commands.rs
  ank/src/cli_commands/apply_manifests.rs
  ank/src/cli_commands/delete_workloads.rs
  ank/src/cli_commands/get_state.rs
  ank/src/cli_commands/get_workloads.rs
  ank/src/cli_commands/run_workload.rs
  ank/src/cli_commands/server_connection.rs
  ank/src/cli_commands/wait_list.rs
  ank/src/cli_commands/workload_table_row.rs
  ank/src/filtered_complete_state.rs
  ank/src/main.rs
  api/Cargo.toml
  api/build.rs
  api/proto/ank_base.proto
  api/src/lib.rs
  common/src/commands.rs
  common/src/from_server_interface.rs
  common/src/objects/state.rs
  common/src/objects/stored_workload_spec.rs
  common/src/objects/workload_states_map.rs
  common/src/state_manipulation/object.rs
  common/src/test_utils.rs
  doc/docs/usage/upgrading/v0_3_to_v0_4.md
  examples/cpp_control_interface/src/main.cpp
  examples/nodejs_control_interface/src/main.js
  examples/python_control_interface/src/main.py
  examples/rust_control_interface/src/main.rs
  grpc/src/from_server_proxy.rs
  grpc/src/grpc_api.rs
  grpc/src/to_server_proxy.rs
  server/Cargo.toml
  server/resources/startConfig.yaml
  server/src/ankaios_server.rs
  server/src/ankaios_server/server_state.rs
Labels: bug, ready for review

#329 Small improvements for mTLS
  .devcontainer/Dockerfile
  agent/src/main.rs
  ank/src/log.rs
  ank/src/main.rs
  doc/docs/reference/complete-state.md
  doc/docs/usage/mtls-setup.md
  doc/docs/usage/quickstart.md
  doc/docs/usage/tutorial-vehicle-signals.md
  examples/run_example.sh
  grpc/src/lib.rs
  server/src/main.rs
  tests/resources/ankaios.resource
  tests/resources/certs/agent-key.pem
  tests/resources/certs/agent.pem
  tests/resources/certs/ca-key.pem
  tests/resources/certs/ca.pem
  tests/resources/certs/cli-key.pem
  tests/resources/certs/cli.pem
  tests/resources/certs/server-key.pem
  tests/resources/certs/server.pem
  tests/resources/variables.resource
  tests/stests/mtls/mtls_communication.robot
  tools/ankaios-docker/agent/Dockerfile
  tools/ankaios-docker/server/Dockerfile
  tools/certs/create_certs.sh
  tools/dev_scripts/ankaios-secure-start
  tools/dev_scripts/ankaios-start
  tools/run_robot_tests.sh
Labels: ignore-for-release, ready for review

#332 Some small fixes for the documentation
  doc/docs/usage/quickstart.md
  tools/ankaios-docker/README.md
Labels: ignore-for-release, ready for review
