Repository eclipse-ankaios/ankaios, pull requests merged in 2024-04, with the labels that each got.

#224 Update dev container for latest MkDocs Material
  .devcontainer/Dockerfile
  .github/workflows/build.yml
  .github/workflows/documentation.yml
  doc/mkdocs.yml
Labels: documentation, ready for review

#223 Introduced setting log level during Ankaios installation
  doc/docs/usage/installation.md
  tools/install.sh
Labels: ready for review

#230 Introduce a requirements description template
  doc/docs/development/requirement-template.md
  doc/docs/development/requirement-tracing.md
  doc/mkdocs.yml
Labels: enhancement, ready for review

#210 Ank CLI waits for server response and correct workload states
  Cargo.lock
  ank/Cargo.toml
  ank/doc/swdesign/README.md
  ank/src/cli.rs
  ank/src/cli_commands.rs
  ank/src/cli_commands/wait_list.rs
  ank/src/log.rs
  ank/src/main.rs
  common/src/objects/mod.rs
  common/src/objects/workload_state.rs
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
  tests/resources/ankaios.resource
  tests/resources/ankaios_library.py
  tests/resources/configs/podman_alpine_sleep.yaml
  tests/stests/manifests/apply_manifests.robot
  tests/stests/workloads/interworkload_dependencies.robot
  tests/stests/workloads/state_operations_with_field_mask.robot
Labels: ready for review

#231 reports 'Removed' on delete workload request for already removed workloads
  agent/src/runtime_manager.rs
Labels: bug, ready for review

#233 Update documentation according to new Ank CLI behaviour
  doc/docs/usage/tutorial-vehicle-signals.md
Labels: documentation, ready for review

#218 First version of upgrading section
  doc/docs/usage/upgrading/v0_2_to_v0_3.md
  doc/mkdocs.yml
Labels: documentation, ready for review

#235 Minor fix for documentation
  doc/docs/usage/quickstart.md
  doc/docs/usage/tutorial-vehicle-signals.md
Labels: ignore-for-release, ready for review

#238 Fix formatting for python example
  examples/python_control_interface/src/main.py
Labels: ready for review

#243 Update version to 0.3.1-pre
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
Labels: ignore-for-release, ready for review

#244 Use static release of podman for Vagrant Ubuntu 22.04
  tools/vagrant/ubuntu22.04/init.sh
Labels: ready for review

#245 Update versions of control interface examples
  examples/nodejs_control_interface/package-lock.json
  examples/nodejs_control_interface/package.json
  examples/rust_control_interface/Cargo.lock
  examples/rust_control_interface/Cargo.toml
Labels: ready for review

#247 Update of failed podman workload leaves old container on the system
  agent/doc/swdesign/README.md
  agent/src/runtime_connectors/podman/podman_runtime.rs
Labels: bug, ready for review

#252 Add hint for automated parsing of workload states
  ank/src/cli.rs
Labels: enhancement, ready for review

#248 Ank apply exits on not scheduled
  .devcontainer/Dockerfile
  .gitignore
  ank/src/cli_commands.rs
  ank/src/cli_commands/wait_list.rs
  common/src/objects/mod.rs
  common/src/objects/workload_instance_name.rs
  tests/resources/ankaios_library.py
  tools/dev_scripts/ankaios-clean
  tools/dev_scripts/ankaios-start
Labels: bug, ready for review

#257 update actions/download-/upload-artifact to v4
  .github/workflows/build.yml
  .github/workflows/release.yml
  doc/docs/development/ci-cd-release.md
  doc/docs/development/ci-cd.md
Labels: ready for review, CI/CD
