Repository eclipse-ankaios/ankaios, pull requests merged in 2024-11, with the labels that each got.

#403 Upgrade app devcontainer base to newer tooling
  doc/docs/development/extending-dev-container.md
  tools/app_dev_container_base/Dockerfile
  tools/app_dev_container_base/README.md
  tools/app_dev_container_base/containers.conf
  tools/app_dev_container_base/dot_bashrc
  tools/app_dev_container_base/dot_tmux.conf
  tools/app_dev_container_base/dot_zshrc
  tools/app_dev_container_base/starship.toml
Labels: ready for review

#400 Add cli commands for config
  ank/doc/swdesign/README.md
  ank/doc/swdesign/plantuml/class_data-structures.plantuml
  ank/doc/swdesign/plantuml/class_data-structures.svg
  ank/doc/swdesign/plantuml/seq_get_config.plantuml
  ank/doc/swdesign/plantuml/seq_get_config.svg
  ank/src/cli.rs
  ank/src/cli_commands.rs
  ank/src/cli_commands/cli_table.rs
  ank/src/cli_commands/config_table_row.rs
  ank/src/cli_commands/delete_configs.rs
  ank/src/cli_commands/delete_workloads.rs
  ank/src/cli_commands/get_configs.rs
  ank/src/main.rs
  common/src/test_utils.rs
  doc/docs/usage/tutorial-vehicle-signals.md
  server/resources/startConfig.yaml
  tests/resources/ankaios.resource
  tests/resources/ankaios_library.py
  tests/resources/configs/default_with_config.yaml
  tests/stests/configs/work_with_configs.robot
Labels: enhancement, ready for review

#346 Adapt SwDD for authorization
  Cargo.lock
  agent/doc/swdesign/README.md
  agent/doc/swdesign/drawio/unit_overview.drawio.svg
  agent/src/control_interface/authorizer.rs
  agent/src/control_interface/authorizer/path_pattern.rs
  agent/src/control_interface/control_interface_info.rs
  agent/src/control_interface/control_interface_task.rs
  agent/src/workload.rs
  tests/resources/image/Cargo.toml
  tests/stests/control_interface/authorization.robot
Labels: ready for review

#410 Add Python SDK to Awesome Ankaios page.
  doc/docs/usage/awesome-ankaios.md
Labels: ignore-for-release, ready for review

#412 Fix usage section
  doc/docs/usage/tutorial-vehicle-signals.md
Labels: ignore-for-release, ready for review

#413 Fix sections in reference chapter
  Cargo.lock
  agent/doc/swdesign/README.md
  ank/src/cli_commands/apply_manifests.rs
  doc/docs/reference/complete-state.md
  doc/docs/reference/control-interface.md
  doc/docs/reference/startup-configuration.md
  server/doc/swdesign/README.md
Labels: ignore-for-release, ready for review

#415 Final preparation of the 0.5.0 release
  Cargo.lock
  agent/Cargo.toml
  ank/Cargo.toml
  api/Cargo.toml
  common/Cargo.toml
  examples/cpp_control_interface/Dockerfile
  examples/nodejs_control_interface/Dockerfile
  examples/python_control_interface/Dockerfile
  examples/rust_control_interface/Dockerfile
  grpc/Cargo.toml
  server/Cargo.toml
  tools/ankaios-docker/agent/Dockerfile
  tools/ankaios-docker/server/Dockerfile
Labels: ignore-for-release
