Repository eclipse-ankaios/ankaios, pull requests merged in 2024-06, with the labels that each got.

#277 Update list of supported operating systems
  doc/docs/usage/installation.md
Labels: documentation, ready for review

#278 Fix wording for ank CLI message
  ank/src/cli_commands.rs
Labels: ready for review

#246 Fix CLI misses messages
  Cargo.lock
  ank/Cargo.toml
  ank/doc/swdesign/README.md
  ank/doc/swdesign/plantuml/seq_cmd_startup.plantuml
  ank/doc/swdesign/plantuml/seq_cmd_startup.svg
  ank/doc/swdesign/plantuml/seq_delete_workload.plantuml
  ank/doc/swdesign/plantuml/seq_delete_workload.svg
  ank/doc/swdesign/plantuml/seq_get_state.plantuml
  ank/doc/swdesign/plantuml/seq_get_state.svg
  ank/doc/swdesign/plantuml/seq_get_workload.plantuml
  ank/doc/swdesign/plantuml/seq_get_workload.svg
  ank/doc/swdesign/plantuml/seq_run_workload.plantuml
  ank/doc/swdesign/plantuml/seq_run_workload.svg
  ank/doc/swdesign/plantuml/seq_set_state.plantuml
  ank/doc/swdesign/plantuml/seq_set_state.svg
  ank/src/cli_commands.rs
  ank/src/cli_commands/apply_manifests.rs
  ank/src/cli_commands/server_connection.rs
Labels: bug, ready for review

#284 283 Fix traces when creating/replacing/deleting workloads
  agent/src/runtime_connectors/cli_command.rs
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/runtime_manager.rs
  agent/src/workload/workload_control_loop.rs
  server/resources/startConfig.yaml
Labels: ignore-for-release, ready for review

#288 Add fix for stopping containers to documentation
  doc/docs/usage/installation.md
Labels: documentation

#271 Optimize CI/CD steps
  .github/workflows/build.yml
  .github/workflows/documentation.yml
  .vscode/settings.json
  tests/stests/workloads/retry_creation_of_workload_podman.robot
Labels: ignore-for-release, ready for review

#293 Bump version to 0.4.0-pre
  Cargo.lock
  Cargo.toml
  agent/Cargo.toml
  ank/Cargo.toml
  api/Cargo.toml
  grpc/Cargo.toml
Labels: ignore-for-release, ready for review

#294 Fix condition for long-runtime system tests and add user doc section
  .github/workflows/build.yml
  doc/docs/development/system-tests.md
Labels: ignore-for-release, ready for review

#295 Fix crash on misbehaving terminals
  ank/src/log.rs
Labels: bug, ready for review

#296 Remove dependencies to URL crate
  Cargo.lock
  agent/Cargo.toml
  agent/src/cli.rs
  agent/src/main.rs
  ank/Cargo.toml
  ank/src/cli.rs
  ank/src/cli_commands.rs
  ank/src/cli_commands/server_connection.rs
  ank/src/log.rs
  ank/src/main.rs
  common/src/communications_error.rs
  grpc/Cargo.toml
  grpc/src/client.rs
  grpc/tests/grpc_test.rs
Labels: ignore-for-release, ready for review

#297 Improve the error message when entering wrong kube down options
  agent/src/runtime_connectors/cli_command.rs
Labels: enhancement, ready for review

#289 Delete startupState from CompleteState
  ank/doc/swdesign/README.md
  ank/src/cli_commands.rs
  api/proto/ank_base.proto
  common/src/commands.rs
  common/src/objects/complete_state.rs
  common/src/state_manipulation/object.rs
  common/src/test_utils.rs
  doc/docs/architecture.md
  doc/docs/reference/complete-state.md
  doc/docs/usage/quickstart.md
  doc/docs/usage/tutorial-vehicle-signals.md
  grpc/src/from_server_proxy.rs
  grpc/src/grpc_api.rs
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
  server/src/ankaios_server/server_state.rs
  tests/stests/workloads/reject_state_with_cyclic_dependencies.robot
Labels: enhancement, ready for review

#300 Move doc files into proper folder
  api/doc/swdesign/README.md
  api/doc/swdesign/drawio/context_view.drawio.svg
  api/doc/swdesign/drawio/unit_overview.drawio.svg
Labels: bug, ignore-for-release

#307 Add awesome Ankaios page
  doc/docs/usage/awesome-ankaios.md
  doc/mkdocs.yml
Labels: documentation, ready for review
