Repository eclipse-ankaios/ankaios, pull requests merged in 2024-08, with the labels that each got.

#335 List meta-ankaios in Awesome Ankaios section
  doc/docs/usage/awesome-ankaios.md
Labels: documentation

#336 Change to individual versions because of bitbake
  Cargo.toml
  agent/Cargo.toml
  ank/Cargo.toml
  common/Cargo.toml
  grpc/Cargo.toml
  server/Cargo.toml
Labels: ignore-for-release, ready for review

#331 Prepare release v0.4.0
  Cargo.lock
  agent/Cargo.toml
  ank/Cargo.toml
  api/Cargo.toml
  common/Cargo.toml
  doc/docs/usage/installation.md
  doc/docs/usage/upgrading/v0_3_to_v0_4.md
  grpc/Cargo.toml
  server/Cargo.toml
  tools/ankaios-docker/agent/Dockerfile
  tools/ankaios-docker/compose.yaml
  tools/ankaios-docker/server/Dockerfile
Labels: ignore-for-release

#342 Add additional information to the upgrading to v0.4.0 section
  doc/docs/usage/upgrading/v0_3_to_v0_4.md
Labels: ignore-for-release

#350 Fix failing grpc integrationtests
  Cargo.lock
  grpc/Cargo.toml
  grpc/tests/grpc_test.rs
Labels: ignore-for-release, ready for review

#340 Unify Ankaios cli
  ank/src/cli.rs
  ank/src/cli_commands/set_state.rs
  ank/src/main.rs
  doc/docs/reference/complete-state.md
  tests/stests/workloads/interworkload_dependencies.robot
  tests/stests/workloads/reject_state_with_cyclic_dependencies.robot
  tests/stests/workloads/retry_creation_of_workload_podman.robot
  tests/stests/workloads/state_operations_with_field_mask.robot
  tests/stests/workloads/update_workload_podman.robot
Labels: enhancement, ready for review

#356 Release branches
  .github/workflows/build.yml
  .github/workflows/documentation.yml
  doc/docs/development/ci-cd-release.md
Labels: documentation, ready for review

#359 349 fix complete state filtering with control interface access
  .vscode/settings.json
  Cargo.lock
  api/Cargo.toml
  api/build.rs
  common/src/objects/control_interface_access.rs
  common/src/objects/mod.rs
  doc/docs/reference/startup-configuration.md
  server/resources/startConfig.yaml
  server/src/ankaios_server/server_state.rs
Labels: ready for review

#361 Prepare release v0.4.1
  .github/workflows/build.yml
  .github/workflows/documentation.yml
  .vscode/settings.json
  Cargo.lock
  agent/Cargo.toml
  ank/Cargo.toml
  api/Cargo.toml
  api/build.rs
  common/Cargo.toml
  common/src/objects/control_interface_access.rs
  common/src/objects/mod.rs
  doc/docs/development/ci-cd-release.md
  doc/docs/reference/startup-configuration.md
  doc/docs/usage/upgrading/v0_3_to_v0_4.md
  grpc/Cargo.toml
  grpc/tests/grpc_test.rs
  server/Cargo.toml
  server/resources/startConfig.yaml
  server/src/ankaios_server/server_state.rs
  tools/ankaios-docker/agent/Dockerfile
  tools/ankaios-docker/compose.yaml
  tools/ankaios-docker/server/Dockerfile
Labels: ignore-for-release

#357 Prevent docker.io images in tests due to rate limit
  .editorconfig
  .github/workflows/build.yml
  .vscode/settings.json
  Makefile
  doc/docs/development/system-tests.md
  tests/resources/configs/control_interface_workload.yaml.template
  tests/resources/configs/create_workload_custom_name.yaml
  tests/resources/configs/create_workloads_with_dependencies_config.yaml
  tests/resources/configs/default.yaml
  tests/resources/configs/default_config_with_dependencies.yaml
  tests/resources/configs/delete_workloads_with_dependencies.yaml
  tests/resources/configs/device_restart_with_dependencies.yaml
  tests/resources/configs/kube.yaml
  tests/resources/configs/manifest1.yaml
  tests/resources/configs/manifest12.yaml
  tests/resources/configs/manifest2.yaml
  tests/resources/configs/manifest_no_agent_name.yaml
  tests/resources/configs/podman_alpine_sleep.yaml
  tests/resources/configs/simple.yaml
  tests/resources/configs/simple_state.yaml
  tests/resources/configs/state_with_dependency_cycle.yaml
  tests/resources/configs/state_with_restart_policies.yaml
  tests/resources/configs/update_state_config_with_dependency_cycle.yaml
  tests/resources/configs/update_state_create_one_workload.yaml
  tests/resources/configs/update_state_invalid_version.yaml
  tests/resources/configs/update_state_missing_version.yaml
  tests/resources/configs/update_state_pending_create.yaml
  tests/resources/configs/update_workloads_pending_create.yaml
  tests/resources/configs/update_workloads_pending_delete.yaml
Labels: ready for review
