Repository eclipse-ankaios/ankaios, pull requests merged in 2024-03, with the labels that each got.

#199 Use explicit stopping state when stopping triggered by Ankaios
  agent/doc/swdesign/README.md
  agent/src/agent_manager.rs
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/workload/workload_control_loop.rs
  api/proto/ankaios.proto
  common/doc/swdesign/README.md
  common/doc/swdesign/drawio/state_workload_execution_all_states.drawio.svg
  common/doc/swdesign/drawio/state_workload_execution_all_states_simple.drawio.svg
  common/doc/swdesign/drawio/state_workload_execution_major_states.drawio.svg
  common/src/objects/workload_state.rs
Labels: bug, ignore-for-release

#204 Remove unused Success response
  api/proto/ankaios.proto
  common/src/commands.rs
  common/src/from_server_interface.rs
Labels: enhancement, ignore-for-release

#198 Add basic performance figures to documentation
  doc/docs/reference/resource-usage.md
  doc/docs/usage/installation.md
  doc/mkdocs.yml
Labels: documentation, ready for review

#197 Format version for workload state in complete state, startup config and ank-apply-manifest
  agent/src/workload_scheduler/scheduler.rs
  ank/doc/swdesign/README.md
  ank/src/cli_commands.rs
  api/proto/ankaios.proto
  common/src/commands.rs
  common/src/from_server_interface.rs
  common/src/objects/complete_state.rs
  common/src/objects/mod.rs
  common/src/objects/state.rs
  common/src/state_manipulation/object.rs
  common/src/test_utils.rs
  common/src/to_server_interface.rs
  doc/docs/reference/complete-state.md
  doc/docs/reference/control-interface.md
  doc/docs/reference/startup-configuration.md
  doc/docs/usage/quickstart.md
  examples/config/startupState.yaml
  examples/cpp_control_interface/src/main.cpp
  examples/nodejs_control_interface/src/main.js
  examples/python_control_interface/src/main.py
  examples/rust_control_interface/src/main.rs
  grpc/src/from_server_proxy.rs
  server/doc/swdesign/README.md
  server/resources/startConfig.yaml
  server/src/ankaios_server.rs
  server/src/ankaios_server/server_state.rs
  tests/resources/configs/create_workload_custom_name.yaml
  tests/resources/configs/create_workloads_with_dependencies_config.yaml
  tests/resources/configs/default.yaml
  tests/resources/configs/default_config_with_dependencies.yaml
  tests/resources/configs/delete_workloads_with_dependencies.yaml
  tests/resources/configs/kube.yaml
  tests/resources/configs/manifest1.yaml
  tests/resources/configs/manifest12.yaml
  tests/resources/configs/manifest2.yaml
  tests/resources/configs/manifest_no_agent_name.yaml
  tests/resources/configs/podman_alpine_sleep.yaml
  tests/resources/configs/podman_wrong_image_name.yaml
  tests/resources/configs/simple.yaml
  tests/resources/configs/state_with_dependency_cycle.yaml
  tests/resources/configs/update_state_config_with_dependency_cycle.yaml
  tests/resources/configs/update_state_create_one_workload.yaml
  tests/resources/configs/update_state_invalid_version.yaml
  tests/resources/configs/update_state_missing_version.yaml
  tests/resources/configs/update_state_pending_create.yaml
  tests/resources/configs/update_workloads_pending_create.yaml
  tests/resources/configs/update_workloads_pending_delete.yaml
  tests/stests/workloads/update_workload_podman.robot
Labels: enhancement, breaking-change, ready for review

#205 Unify error handling for missing fields in Ankaios manifests
  ank/doc/swdesign/README.md
  ank/src/cli_commands.rs
Labels: ready for review

#209 Startup config does not check `apiVersion`
  server/src/ankaios_server.rs
Labels: bug, ready for review

#195 Add requirements and linkage for inter-workload dependencies implementation in agent
  agent/doc/swdesign/README.md
  agent/doc/swdesign/drawio/unit_overview.drawio.svg
  agent/doc/swdesign/plantuml/seq_inter-workload_dependencies.plantuml
  agent/doc/swdesign/plantuml/seq_inter-workload_dependencies.svg
  agent/doc/swdesign/plantuml/seq_inter-workload_dependencies_on_update_workload_state.plantuml
  agent/doc/swdesign/plantuml/seq_inter-workload_dependencies_on_update_workload_state.svg
  agent/doc/swdesign/plantuml/seq_store_own_workload_state.plantuml
  agent/doc/swdesign/plantuml/seq_store_own_workload_state.svg
  agent/doc/swdesign/plantuml/seq_store_workload_state.plantuml
  agent/doc/swdesign/plantuml/seq_store_workload_state.svg
  agent/doc/swdesign/plantuml/seq_update_workload.plantuml
  agent/doc/swdesign/plantuml/seq_update_workload.svg
  agent/doc/swdesign/plantuml/seq_update_workload_initial.plantuml
  agent/doc/swdesign/plantuml/seq_update_workload_initial.svg
  agent/src/agent_manager.rs
  agent/src/main.rs
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/runtime_manager.rs
  agent/src/workload/workload_control_loop.rs
  agent/src/workload_operation.rs
  agent/src/workload_scheduler/dependency_state_validator.rs
  agent/src/workload_scheduler/scheduler.rs
  common/src/objects/stored_workload_spec.rs
  common/src/objects/workload_spec.rs
  server/src/ankaios_server.rs
  server/src/ankaios_server/server_state.rs
  tests/stests/workloads/interworkload_dependencies.robot
Labels: ignore-for-release

#206 add r/w permissions for others on ankaios default base path e.g.
  Cargo.lock
  agent/Cargo.toml
  agent/src/cli.rs
  agent/src/control_interface/filesystem.rs
Labels: ready for review

#214 Fix installation script
  .vscode/settings.json
  tools/install.sh
Labels: ignore-for-release

#213 Extend user documentation with inter-workload dependencies
  doc/docs/reference/inter-workload-dependencies.md
  doc/mkdocs.yml
Labels: documentation

#215 Fix removed linkage for handling initial workloads
  agent/src/runtime_manager.rs
Labels: ignore-for-release

#157 Add user tutorial
  .markdownlint.yml
  doc/docs/assets/speed-provider.png
  doc/docs/assets/tutorial_vehicle_signals_overview.png
  doc/docs/usage/quickstart.md
  doc/docs/usage/tutorial-vehicle-signals.md
  doc/mkdocs.yml
  tools/tutorial_vehicle_signals/speed-consumer/Dockerfile
  tools/tutorial_vehicle_signals/speed-consumer/README.md
  tools/tutorial_vehicle_signals/speed-consumer/requirements.txt
  tools/tutorial_vehicle_signals/speed-consumer/speed-consumer.py
  tools/tutorial_vehicle_signals/speed-provider/Dockerfile
  tools/tutorial_vehicle_signals/speed-provider/README.md
  tools/tutorial_vehicle_signals/speed-provider/requirements.txt
  tools/tutorial_vehicle_signals/speed-provider/speed-provider.py
  tools/tutorial_vehicle_signals/speed-provider/templates/index.html
Labels: documentation, ready for review
