Repository eclipse-ankaios/ankaios, pull requests merged in 2024-05, with the labels that each got.

#253 Documentation: SVGs hard to read in dark mode
  doc/docs/architecture.md
  doc/docs/assets/architecture_overview.png
  doc/docs/assets/architecture_overview.svg
  doc/docs/assets/architecture_sequence.png
  doc/docs/assets/architecture_sequence.svg
  doc/docs/assets/length-delimited-protobuf-layout.png
  doc/docs/assets/tutorial_vehicle_signals_overview.png
  doc/docs/reference/control-interface.md
Labels: documentation, ready for review

#249 Add restart policy handling for workloads
  agent/doc/swdesign/README.md
  agent/doc/swdesign/plantuml/seq_store_own_workload_state.plantuml
  agent/doc/swdesign/plantuml/seq_store_own_workload_state.svg
  agent/src/agent_manager.rs
  agent/src/generic_polling_state_checker.rs
  agent/src/runtime_connectors/runtime_connector.rs
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/workload.rs
  agent/src/workload/control_loop_state.rs
  agent/src/workload/workload_command_channel.rs
  agent/src/workload/workload_control_loop.rs
  common/src/objects/workload_spec.rs
  doc/docs/reference/restart-policy.md
  doc/mkdocs.yml
  tests/resources/ankaios.resource
  tests/resources/ankaios_library.py
  tests/resources/configs/state_with_restart_policies.yaml
  tests/stests/workloads/interworkload_dependencies.robot
  tests/stests/workloads/restart_handling_podman.robot
  tests/stests/workloads/restart_handling_podman_kube.robot
Labels: enhancement, ready for review

#270 Add Slack workspace to documentation
  doc/docs/support.md
Labels: documentation, ready for review

#268 Extend build instructions for dev container
  doc/docs/development/extending-dev-container.md
Labels: documentation, ready for review

#265 Handle dependencies when reusing workloads on initial startup
  agent/doc/swdesign/README.md
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
  agent/src/runtime_connectors/runtime_connector.rs
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/runtime_manager.rs
  common/doc/swdesign/drawio/state_workload_execution_all_states.drawio.svg
  common/doc/swdesign/plantuml/state_workload_execution_states.plantuml
  common/doc/swdesign/plantuml/state_workload_execution_states.svg
  tests/resources/ankaios.resource
  tests/resources/ankaios_library.py
  tests/resources/configs/device_restart_with_dependencies.yaml
  tests/resources/configs/state_with_restart_policies.yaml
  tests/stests/workloads/device_restart_with_dependencies.robot
  tests/stests/workloads/interworkload_dependencies.robot
  tests/stests/workloads/restart_handling_podman.robot
  tests/stests/workloads/restart_handling_podman_kube.robot
Labels: bug, ignore-for-release, ready for review

#269 Ank CLI run workload and delete workload use wrong requests
  ank/doc/swdesign/README.md
  ank/doc/swdesign/plantuml/seq_delete_workload.plantuml
  ank/doc/swdesign/plantuml/seq_delete_workload.svg
  ank/doc/swdesign/plantuml/seq_run_workload.plantuml
  ank/doc/swdesign/plantuml/seq_run_workload.svg
  ank/src/cli_commands.rs
Labels: bug, ready for review
