Repository eclipse-ankaios/ankaios, pull requests merged in 2025-01, with the labels that each got.

#428 Fix wildcard auth rule for empty filed masks
  agent/doc/swdesign/README.md
  agent/src/control_interface/authorizer.rs
  agent/src/control_interface/authorizer/path_pattern.rs
  agent/src/control_interface/control_interface_task.rs
  justfile
Labels: bug, ready for review

#438 Fix high resource usage while sampling resource usage
  agent/src/agent_manager.rs
Labels: bug, ready for review

#435 Bump version to 0.6.0-pre
  Cargo.lock
  agent/Cargo.toml
  ank/Cargo.toml
  api/Cargo.toml
  common/Cargo.toml
  examples/cpp_control_interface/Dockerfile
  examples/nodejs_control_interface/Dockerfile
  examples/python_control_interface/Dockerfile
  examples/rust_control_interface/Dockerfile
  grpc/Cargo.toml
  server/Cargo.toml
Labels: ignore-for-release, ready for review

#434 Pull out and improve agent io utils (filesystem, directory, etc.)
  agent/src/cli.rs
  agent/src/control_interface.rs
  agent/src/control_interface/fifo.rs
  agent/src/control_interface/input_output.rs
  agent/src/io_utils/dir_utils.rs
  agent/src/io_utils/directory.rs
  agent/src/io_utils/fs.rs
  agent/src/io_utils/mod.rs
  agent/src/main.rs
Labels: ignore-for-release, ready for review

#440 Add new project to Awesome Ankaios page
  doc/docs/usage/awesome-ankaios.md
Labels: documentation, ready for review
