Repository eclipse-ankaios/ankaios, pull requests merged in 2025-02, with the labels that each got.

#449 Add missing requirement version
  agent/doc/swdesign/README.md
  agent/src/runtime_manager.rs
  agent/src/workload_scheduler/scheduler.rs
  tests/stests/workloads/interworkload_dependencies.robot
Labels: ignore-for-release, ready for review

#448 Fix the handling of unneeded workloads at server restart
  agent/doc/swdesign/README.md
  agent/src/runtime_manager.rs
Labels: bug, ready for review

#445 Add support for auto line indentation of multi line config to ConfigRenderer
  agent/src/agent_manager.rs
  doc/docs/usage/manifest/config-rendering.md
  doc/mkdocs.yml
  server/doc/swdesign/README.md
  server/src/ankaios_server/config_renderer.rs
  tests/resources/configs/manifest_with_multi_line_config.yaml
  tests/stests/workloads/workload_configs_podman_kube.robot
Labels: enhancement, ready for review

#451 Update readme and contributing
  CONTRIBUTING.md
  README.md
  doc/docs/index.md
Labels: ignore-for-release, ready for review

#447 Update fleet management tutorial
  Cargo.lock
  agent/Cargo.toml
  agent/src/control_interface/control_interface_task.rs
  common/src/helpers.rs
  doc/docs/usage/tutorial-fleet-management.md
  tools/tutorial_fleet_management/fleet-connector/requirements.txt
Labels: ready for review

#443 Prepare release 0.5.1
  Cargo.lock
  agent/Cargo.toml
  agent/doc/swdesign/README.md
  agent/src/agent_manager.rs
  agent/src/cli.rs
  agent/src/control_interface.rs
  agent/src/control_interface/authorizer.rs
  agent/src/control_interface/authorizer/path_pattern.rs
  agent/src/control_interface/control_interface_task.rs
  agent/src/control_interface/directory.rs
  agent/src/control_interface/filesystem.rs
  agent/src/main.rs
  ank/Cargo.toml
  api/Cargo.toml
  common/Cargo.toml
  common/src/helpers.rs
  doc/docs/usage/tutorial-fleet-management.md
  examples/cpp_control_interface/Dockerfile
  examples/nodejs_control_interface/Dockerfile
  examples/python_control_interface/Dockerfile
  examples/rust_control_interface/Dockerfile
  grpc/Cargo.toml
  justfile
  server/Cargo.toml
  tools/generate_test_coverage_report.sh
  tools/tutorial_fleet_management/fleet-connector/requirements.txt
Labels: ready for review

#458 Fix disappearing logo in light mode
  doc/docs/index.md
  doc/mkdocs.yml
Labels: documentation, ready for review

#424 Ankaios server config files
  .devcontainer/devcontainer.json
  Cargo.lock
  agent/config/ank-agent.conf
  ank/config/ank.conf
  common/Cargo.toml
  common/src/state_manipulation/object.rs
  grpc/src/client.rs
  grpc/src/lib.rs
  grpc/src/server.rs
  grpc/tests/grpc_test.rs
  server/Cargo.toml
  server/config/ank-server.conf
  server/doc/swdesign/README.md
  server/doc/swdesign/plantuml/seq_startup.plantuml
  server/doc/swdesign/plantuml/seq_startup.svg
  server/src/ankaios_server.rs
  server/src/cli.rs
  server/src/main.rs
  server/src/server_config.rs
  tests/resources/ankaios.resource
  tests/resources/configs/ank-server-default.conf
  tests/resources/configs/ank-server.conf
  tests/resources/configs/ank-server_with_certificates_paths.conf
  tests/stests/configs/config_file.robot
Labels: enhancement, ready for review
