Repository eclipse-ankaios/ankaios, pull requests merged in 2025-06, with the labels that each got.

#504 Add stderr logs
  agent/src/runtime_connectors/generic_log_collector.rs
  agent/src/runtime_connectors/log_collector.rs
  agent/src/runtime_connectors/log_collector_subscription.rs
  agent/src/runtime_connectors/podman/mod.rs
  agent/src/runtime_connectors/podman/podman_log_collector.rs
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_log_collector.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
Labels: ready for review

#505 Fix swdd id for ank get workloads with watch option
  ank/doc/swdesign/README.md
  ank/src/main.rs
Labels: ignore-for-release, ready for review

#497 Fix LogEntry proto message numbers
  api/proto/ank_base.proto
Labels: ignore-for-release
