Repository eclipse-ankaios/ankaios, pull requests merged in 2025-04, with the labels that each got.

#471 Add required footer items for Eclipse Foundation
  doc/docs/assets/eclipse-foundation.png
  doc/overrides/main.html
Labels: documentation, ready for review

#473 Update the awesome ankaios page with symphony
  Cargo.lock
  doc/docs/usage/awesome-ankaios.md
Labels: documentation, ready for review

#468 Create test reports and store as release artifacts
  .github/workflows/build.yml
  .github/workflows/release.yml
  justfile
  nextest.toml
  tools/create_release.sh
  tools/run_robot_tests.sh
Labels: ready for review

#469 Add quality manifest as release artifact
  .github/workflows/release.yml
Labels: ready for review

#472 Support config files installation
  .github/workflows/release.yml
  Cargo.lock
  agent/config/ank-agent.conf
  ank/config/ank.conf
  doc/docs/reference/config-files.md
  doc/docs/usage/installation.md
  doc/docs/usage/mtls-setup.md
  doc/mkdocs.yml
  server/config/ank-server.conf
  tools/create_artifacts.sh
  tools/create_configs.sh
  tools/create_release.sh
  tools/install.sh
Labels: ready for review

#481 Stabilize the utests for the config files by adding a mutex
  agent/src/main.rs
  ank/src/main.rs
  server/src/main.rs
Labels: ignore-for-release, ready for review

#475 Fix server to not crash on missing hello message
  grpc/src/grpc_agent_connection.rs
  grpc/src/grpc_cli_connection.rs
Labels: ready for review

#476 Update base dev container
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.base
  .devcontainer/devcontainer.json
  .github/workflows/build.yml
  .github/workflows/documentation.yml
  .vscode/settings.json
  agent/src/runtime_connectors/podman_cli.rs
  agent/src/workload.rs
  agent/src/workload/retry_manager.rs
  agent/src/workload_scheduler/dependency_state_validator.rs
  ank/src/cli_commands.rs
  ank/src/cli_commands/workload_table_row.rs
  server/src/ankaios_server.rs
  server/src/ankaios_server/cycle_check.rs
Labels: ignore-for-release
