Repository eclipse-ankaios/ankaios, pull requests merged in 2025-07, with the labels that each got.

#499 Implement ank cli log collection
  agent/src/agent_manager.rs
  agent/src/runtime_connectors/log_channel.rs
  agent/src/runtime_connectors/log_collector.rs
  ank/doc/swdesign/README.md
  ank/doc/swdesign/plantuml/seq_get_logs.plantuml
  ank/doc/swdesign/plantuml/seq_get_logs.svg
  ank/src/cli.rs
  ank/src/cli_commands.rs
  ank/src/cli_commands/get_logs.rs
  ank/src/cli_commands/server_connection.rs
  ank/src/cli_signals.rs
  ank/src/main.rs
  api/proto/ank_base.proto
  common/src/from_server_interface.rs
  common/src/to_server_interface.rs
  grpc/proto/grpc_api.proto
  grpc/src/grpc_api.rs
  grpc/src/to_server_proxy.rs
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
  tests/resources/ankaios.resource
  tests/resources/configs/workload_logs.yaml
  tests/stests/workloads/workload_files.robot
  tests/stests/workloads/workload_logs.robot
Labels: sub task, ready for review

#511 Cancel log collection on broken collector
  agent/doc/swdesign/README.md
  agent/src/control_interface.rs
  agent/src/control_interface/control_interface_task.rs
  agent/src/control_interface/input_pipe.rs
  agent/src/control_interface/output_pipe.rs
  api/proto/ank_base.proto
  common/src/commands.rs
Labels: ready for review

#492 Handle invalid runtime
  agent/doc/swdesign/README.md
  agent/src/runtime_connectors/dummy_state_checker.rs
  agent/src/runtime_connectors/mod.rs
  agent/src/runtime_connectors/runtime_facade.rs
  agent/src/runtime_connectors/unsupported_runtime.rs
  agent/src/runtime_manager.rs
  doc/docs/reference/complete-state.md
  tests/resources/configs/simple_with_invalid_runtime.yaml
  tests/stests/workloads/add_update_invalid_runtime.robot
Labels: enhancement, ready for review

#514 LogsRequest server validation and LogsRequestAccepted response
  api/proto/ank_base.proto
  common/src/from_server_interface.rs
  server/src/ankaios_server.rs
  server/src/ankaios_server/server_state.rs
Labels: sub task, ready for review

#522 Adapt tutorial for getting logs
  api/proto/control_api.proto
  doc/docs/usage/quickstart.md
  doc/docs/usage/tutorial-fleet-management.md
  doc/docs/usage/tutorial-vehicle-signals.md
Labels: ready for review

#523 Reset agent log subscription store when server is gone
  agent/doc/swdesign/README.md
  agent/src/agent_manager.rs
  agent/src/subscription_store.rs
  common/src/from_server_interface.rs
  grpc/doc/swdesign/README.md
  grpc/src/client.rs
  grpc/src/from_server_proxy.rs
Labels: sub task, ready for review

#529 Handle LogsRequestAccepted messages in Ank CLI
  ank/doc/swdesign/README.md
  ank/src/cli_commands/server_connection.rs
Labels: sub task, ready for review

#531 Workload logs - add missing requirements part 1
  agent/doc/swdesign/README.md
  agent/src/agent_manager.rs
  agent/src/control_interface/authorizer.rs
  agent/src/control_interface/authorizer/rules.rs
  grpc/doc/swdesign/README.md
  server/doc/swdesign/README.md
  server/src/ankaios_server.rs
  server/src/ankaios_server/log_campaign_store.rs
  server/src/ankaios_server/server_state.rs
Labels: ready for review

#537 Adding upgrading to v0.6 section
  doc/docs/usage/upgrading/v0_5_to_v0_6.md
  doc/mkdocs.yml
Labels: ready for review

#542 Add python sdk logging example
  examples/README.md
  examples/cleanup.sh
  examples/cpp_control_interface/startupState.yaml
  examples/nodejs_control_interface/startupState.yaml
  examples/python_control_interface/startupState.yaml
  examples/python_sdk_logging/.gitignore
  examples/python_sdk_logging/Dockerfile
  examples/python_sdk_logging/README.md
  examples/python_sdk_logging/setup_python_sdk.sh
  examples/python_sdk_logging/src/main.py
  examples/python_sdk_logging/startupState.yaml
  examples/run_example.sh
  examples/rust_control_interface/startupState.yaml
  examples/sleepy/Dockerfile
  examples/sleepy/startupState.yaml
Labels: ready for review

#544 Fix authorizer edgecase
  agent/src/control_interface/authorizer/rules.rs
Labels: sub task, minor, ready for review

#535 Workload logs - add missing requirements part 2
  agent/doc/swdesign/README.md
  agent/src/control_interface/authorizer/rules.rs
  agent/src/runtime_connectors/log_picking/generic_log_picker.rs
  agent/src/runtime_connectors/log_picking/log_channel.rs
  agent/src/runtime_connectors/log_picking/log_picker.rs
  agent/src/runtime_connectors/log_picking/log_picking_runner.rs
  agent/src/runtime_connectors/podman/podman_log_picker.rs
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
  agent/src/runtime_connectors/runtime_connector.rs
  agent/src/runtime_manager.rs
  agent/src/subscription_store.rs
  agent/src/workload.rs
  agent/src/workload/workload_command_channel.rs
  agent/src/workload/workload_control_loop.rs
  agent/src/workload_log_facade.rs
  common/doc/swdesign/README.md
  common/src/objects/control_interface_access.rs
  doc/docs/development/requirement-tracing.md
Labels: ready for review

#548 Rename startupState to manifest.yaml
  examples/cpp_control_interface/manifest.yaml
  examples/nodejs_control_interface/manifest.yaml
  examples/python_control_interface/manifest.yaml
  examples/python_sdk_logging/manifest.yaml
  examples/run_example.sh
  examples/rust_control_interface/manifest.yaml
  examples/sleepy/manifest.yaml
Labels: ignore-for-release, ready for review

#552 Fix the req prefixing for the logging
  agent/doc/swdesign/README.md
  agent/src/runtime_connectors/log_fetching/generic_log_fetcher.rs
  agent/src/runtime_connectors/log_fetching/log_channel.rs
  agent/src/runtime_connectors/log_fetching/log_fetcher.rs
  agent/src/runtime_connectors/log_fetching/log_fetching_runner.rs
  agent/src/runtime_connectors/podman/podman_runtime.rs
  agent/src/runtime_connectors/podman_kube/podman_kube_runtime.rs
  agent/src/runtime_connectors/runtime_connector.rs
  agent/src/runtime_manager.rs
  agent/src/subscription_store.rs
  agent/src/workload/workload_control_loop.rs
  agent/src/workload_log_facade.rs
  ank/doc/swdesign/README.md
  ank/src/cli_commands/server_connection.rs
  server/doc/swdesign/README.md
  server/src/ankaios_server/log_campaign_store.rs
Labels: ignore-for-release, ready for review

#553 Prepare release 0.6.0-rc1
  Cargo.lock
  agent/Cargo.toml
  ank/Cargo.toml
  api/Cargo.toml
  common/Cargo.toml
  doc/docs/usage/installation.md
  examples/cpp_control_interface/Dockerfile
  examples/nodejs_control_interface/Dockerfile
  examples/python_control_interface/Dockerfile
  examples/python_sdk_interactive/Dockerfile
  examples/python_sdk_logging/Dockerfile
  examples/rust_control_interface/Dockerfile
  grpc/Cargo.toml
  server/Cargo.toml
  tools/ankaios-docker/agent/Dockerfile
  tools/ankaios-docker/server/Dockerfile
  tools/update_version.sh
  tools/vagrant/ubuntu20.04/Vagrantfile
  tools/vagrant/ubuntu20.04/init.sh
Labels: ignore-for-release, ready for review
