Repository eclipse-ankaios/ankaios, pull requests merged in 2025-05, with the labels that each got.

#479 Check for dead links when building documentation
  doc/README.md
  doc/docs/development/self-service.md
  doc/docs/development/unit-verification.md
  doc/docs/reference/control-interface.md
  doc/mkdocs.yml
Labels: documentation, ready for review

#484 Fix unstable unit tests
  agent/src/agent_config.rs
  agent/src/main.rs
  ank/src/ank_config.rs
  ank/src/main.rs
  server/src/main.rs
  server/src/server_config.rs
Labels: ignore-for-release, ready for review

#491 Update quevee action to v1.0.0
  .github/workflows/release.yml
Labels: ignore-for-release, ready for review

#485 Provided source package including dependencies with each release
  .github/actions/use-vendored-source/action.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  justfile
  tools/check_copyright_headers.sh
Labels: ready for review

#486 Update docs such that latest release is always valid
  doc/docs/development/ci-cd-release.md
Labels: documentation, ready for review

#463 Add watch option to 'ank get workloads' command
  ank/doc/swdesign/README.md
  ank/src/cli.rs
  ank/src/cli_commands.rs
  ank/src/cli_commands/apply_manifests.rs
  ank/src/cli_commands/delete_workloads.rs
  ank/src/cli_commands/get_workloads.rs
  ank/src/cli_commands/run_workload.rs
  ank/src/cli_commands/workload_table_row.rs
  ank/src/main.rs
Labels: enhancement, ready for review
